name: Update Notebooks
on:
  schedule:
    - cron:  '*/60 * * * *'
  push:
    branches:
      - master 
  pull_request: 

jobs:
  update-notebooks:
    runs-on: ubuntu-latest
    steps:
  
    - name: See event name
      run: |
        echo "${EVENT}"
      env:
        EVENT: ${{ github.event_name }}
    
    - name: Copy Repository Contents
      uses: actions/checkout@v2

    - name: Set up Python
      if: github.event_name != 'push'
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Setup Node
      if: github.event_name != 'push'
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      
    - name: install plotly js dependencies
      if: github.event_name != 'push'
      run: npm install -g electron@6.1.4 orca

    - name: run notebooks
      run: |
        pip install bs4 unidecode PyPDF2 matplotlib pandas seaborn papermill ipykernel jupyter folium plotnine psutil arviz xlrd altair jinja2
        python3 -m ipykernel install --user --name python3
        sudo chmod -R 777 .
        cd _notebooks
        ls *.ipynb
        papermill --log-output --kernel python3 2020-03-24-visualizando-los-datos-del-informe-diario.ipynb 2020-03-24-visualizando-los-datos-del-informe-diario.ipynb
        papermill --log-output --kernel python3 2020-03-24-home.ipynb 2020-03-24-home.ipynb
        papermill --log-output --kernel python3 2020-03-24-argentina-en-contexto.ipynb 2020-03-24-argentina-en-contexto.ipynb

    - name: run notebooks - modeling
      if: github.event_name == 'schedule'
      run: |
        sudo chmod -R 777 .
        cd _notebooks

    - name: save files
      if: github.event_name == 'schedule'
      run: |
        git config --global user.email "elsonidoq@gmail.com"
        git config --global user.name "elsonidoq"
        git add _notebooks/
        git add images/
        git commit -m'updated JHU notebooks'
        git push -f

    - name: convert notebooks and word docs to posts
      uses: ./_action_files

    - name: setup directories for Jekyll build
      run: |
        rm -rf _site
        sudo chmod -R 777 .

    - name: Jekyll build
      uses: docker://hamelsmu/fastpages-jekyll
      with:
        args: bash -c "gem install bundler && jekyll build -V"
      env:
        JEKYLL_ENV: 'production'
        
    - name: copy CNAME file into _site if CNAME exists
      if: github.event_name != 'pull_request'
      run: |
        sudo chmod -R 777 _site/
        cp CNAME _site/ 2>/dev/null || :
        
    - name: Deploy
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        publish_dir: ./_site
